language: julia
sudo: required

before_install:
    - (sudo pip3 install setuptools==24.0.3)
install:
    - (sudo pip3 install uproot)
os:
    - linux
julia:
    - 1.0
notifications:
    email: false
