language: julia
sudo: required

before_install:
    - (sudo apt-get -qq update && sudo apt-get install -y python python-pip && sudo pip install --upgrade pip && sudo pip install --upgrade setuptools_scm)
install:
    - (sudo pip install uproot)
os:
    - linux
julia:
    - 1.0
notifications:
    email: false
