language: julia
sudo: required

before_install:
    - (sudo apt-get -qq update && sudo apt-get install -y python3 python3-pip && sudo pip3 install --upgrade setuptools_scm && sudo pip3 install uproot)
os:
    - linux
julia:
    - 1.0
notifications:
    email: false
